<?php

namespace CervezasBundle\Repository;

/**
 * CervezasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CervezasRepository extends \Doctrine\ORM\EntityRepository
{
}
